[tools]
actionlint = "1.7.12"
go = "1.26.5"
golangci-lint = "2.12.2"
lefthook = "2.1.10"
oxfmt = "0.61.0"
zizmor = "1.28.0"

[tasks.fmt]
description = "Run go fmt against code"
run = "go fmt ./..."

[tasks.vet]
description = "Run go vet against code"
run = "go vet ./..."

[tasks.test]
description = "Run tests with coverage"
run = "go test $(go list ./...) -coverprofile cover.out"

[tasks.lint]
description = "Run golangci-lint"
run = "golangci-lint run"

[tasks.lint-fix]
description = "Run golangci-lint with --fix"
run = "golangci-lint run --fix"

[hooks]
postinstall = "lefthook install"
