---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name != 'release' }}

jobs:
  versions:
    name: Versions
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    outputs:
      go-version: ${{ steps.versions.outputs.go-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Mise
        uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # v4.2.4
        with:
          cache: false
          experimental: true
          install: false

      - name: Resolve versions
        id: versions
        run: echo "go-version=$(mise config get tools.go)" >> "$GITHUB_OUTPUT"

  release:
    name: Release
    needs: versions
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: docker/github-builder/.github/workflows/build.yml@27ade872c1e2296e62ef15ab3b10d37665e57cf7 # v1.15.0
    with:
      build-args: |
        VERSION=${{ github.ref_name }}
        REVISION=${{ github.sha }}
        GO_VERSION=${{ needs.versions.outputs.go-version }}
      meta-images: ghcr.io/${{ github.repository }}
      meta-tags: |
        type=semver,pattern={{version}}
        type=raw,value=rolling,enable=${{ github.event_name == 'release' }}
        type=ref,event=branch
      output: image
      platforms: linux/amd64,linux/arm64
      push: true
      sbom: true
      set-meta-annotations: true
      set-meta-labels: true
      sign: true
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
