---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  release:
    name: Release
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: docker/github-builder/.github/workflows/build.yml@17bd7d64200cae4ba58ffc099934e8012ae320f2 # v1.10.0
    with:
      build-args: |
        VERSION=${{ github.ref_name }}
        REVISION=${{ github.sha }}
      meta-images: ghcr.io/${{ github.repository }}
      meta-tags: |
        type=semver,pattern={{version}}
        type=raw,value=rolling,enable=${{ github.event_name == 'release' }}
        type=ref,event=branch
      output: image
      platforms: linux/amd64,linux/arm64
      push: true
      sbom: true
      sign: true
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
