---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".release-please-manifest.json"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".release-please-manifest.json"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  test:
    name: Go Tests
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Mise
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
        with:
          experimental: true
          install_args: --locked

      - name: Check go.mod tidiness
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Run unit tests
        run: mise run test
